stages:
  - build
  - test
  - test_installer
  - test_hardware
  - deploy
  
# Default build
build:2018_R1:
    tags:
     - vivado
     - matlab
    stage: build
    script:
     - cd CI/scripts
     - make build
     - make add_libad9361
     - make gen_tlbx
     - cd ../..
     - mkdir mltbx
     - ls *.mltbx
     - cp *.mltbx mltbx/
    artifacts:
        paths:
            - hdl_wa_bsp/
            - mltbx/
            - deps/

# Future branches
build:master:
    tags:
     - vivado
     - matlab
    stage: build
    script:
     - cd CI/scripts
     - make build MLRELEASE=R2018b HDLBRANCH=master
     - cd ../..
    allow_failure: true
    artifacts:
        paths:
            - hdl_wa_bsp/

# Test HWA no install
test:2018_R1:
    tags:
     - vivado
     - matlab
    stage: test
    dependencies:
     - build:2018_R1
    script:
     - cd CI/scripts
     - make test
     - make zip
    artifacts:
        paths:
            - zip/
        reports:
            junit: test/BSPTestResults.xml

# Test HWA with install
test_installer:2018_R1_Installer:
    tags:
     - vivado
     - matlab
    stage: test_installer
    dependencies:
     - build:2018_R1
    script:
     - cp mltbx/* .
     - pwd
     - ls
     - ls *.mltbx
     - cd CI/scripts
     - make test_installer
    artifacts:
        paths:
            - mltbx/
            - zip/
        reports:
            junit: test/BSPTestResults.xml

# Test streaming interfaces with hardware
test_hardware:Streaming_Hardware:
    only:
     - schedules
    tags:
     - matlab
     - hardware
    stage: test_hardware
    dependencies:
     - build:2018_R1
    script:
     - cd CI/scripts
     - make test_streaming
    artifacts:
        paths:
            - logs/

# Test streaming interfaces with hardware manual
test_manual:Streaming_Hardware_Manual:
    when: manual
    tags:
     - matlab
     - hardware
    script:
     - cd CI/scripts
     - make add_libad9361
     - make test_streaming
    artifacts:
        paths:
            - logs/
            - Report.pdf

# Deploy
deploy:
    tags:
     - matlab
    stage: deploy
    dependencies:
     - test:2018_R1
     - test_installer:2018_R1_Installer
    script:
     - echo "Complete"
    artifacts:
        paths:
            - mltbx/


