stages:
  - build
  - test
  - test_hardware
  - deploy
  
# Default build
build:2018_R1:
    when: manual
    tags:
     - vivado
     - matlab
    stage: build
    script:
     - ./CI/scripts/dockermake build
     - ./CI/scripts/dockermake add_libad9361
     - ./CI/scripts/dockermake gen_tlbx
     - mkdir mltbx
     - ls *.mltbx
     - cp *.mltbx mltbx/
    artifacts:
        paths:
            - hdl_wa_bsp/
            - mltbx/
            - deps/

# Future branches
build:master:
    when: manual
    tags:
     - vivado
     - matlab
    stage: build
    script:
     - export HDLBRANCH=master
     - export MLRELEASE=R2018b
     - ./CI/scripts/dockermake build
     - export HDLBRANCH=
     - export MLRELEASE=
    allow_failure: true
    artifacts:
        paths:
            - hdl_wa_bsp/

# Test HWA no install
test:2018_R1:
    when: manual
    tags:
     - vivado
     - matlab
    stage: test
    dependencies:
     - build:2018_R1
    script:
     - ./CI/scripts/dockermake test
     - ./CI/scripts/dockermake zip
    artifacts:
        paths:
            - zip/
        reports:
            junit: test/BSPTestResults.xml

# Test HWA with install
test_installer:2018_R1_Installer:
    when: manual
    tags:
     - vivado
     - matlab
    stage: test
    dependencies:
     - build:2018_R1
    script:
     - cp mltbx/* .
     - pwd
     - ls
     - ls *.mltbx
     - ./CI/scripts/dockermake test_installer
    artifacts:
        paths:
            - mltbx/
            - zip/
        reports:
            junit: test/BSPTestResults.xml

# Test weekly fully sythesized design
test:Synthesize:
    when: manual
    tags:
     - matlab
     - vivado
    stage: test
    dependencies:
     - build:2018_R1
    script:
     - ./CI/scripts/dockermake test_synth
    artifacts:
        when: always
        name: "$CI_COMMIT_REF_NAME"
        paths:
            - test/
            - Report.pdf

# Test streaming interfaces with hardware
test_hardware:Streaming_Hardware:
    when: manual
    tags:
     - matlab
     - hardware
    stage: test_hardware
    dependencies:
     - build:2018_R1
    script:
     - cd CI/scripts
     - make test_streaming
    artifacts:
        paths:
            - logs/
            - Report.pdf

# Test EVM performance with hardware
test_hardware:EVM_Hardware:
    when: manual
    only:
     - schedules
    tags:
     - matlab
     - hardware
    stage: test_hardware
    dependencies:
     - build:2018_R1
    script:
     - cd CI/scripts
     - make test_evm
    artifacts:
        paths:
            - logs/
            - Report.pdf

# Deploy
deploy:mltbx:
    when: manual
    tags:
     - matlab
    stage: deploy
    dependencies:
     - test:2018_R1
     - test_installer:2018_R1_Installer
    script:
     - echo "Complete"
    artifacts:
        paths:
            - mltbx/
# Doc
pages:
    tags:
     - matlab
    stage: deploy
    script:
     - mkdir public
     - cp -r doc/*.html public
     - cd public
     - tree -H '.' -L 1 --noreport --charset utf-8 > index.html
    artifacts:
        paths:
         - public
    only:
     - doc

