image: ubuntu:18.04

before_script:
  - apt update
  - DEBIAN_FRONTEND=noninteractive apt-get install -y libpng-dev libfreetype6-dev libblas-dev liblapack-dev gfortran build-essential xorg
  - DEBIAN_FRONTEND=noninteractive apt-get install -y openjdk-8-jre openjdk-8-jdk libgtk2.0-0 libxss1 libxt6 zip unzip curl wget tar git
  - apt install net-tools
  - ifconfig eth0 hw ether $ADDR
  - cp -r /mlhspro /mlhsp
  - cp -r /root/.matlabro /root/.matlab

stages:
  - build
  - test
  - test_installer
  - test_hardware
  - deploy
  
# Default build
build:2018_R1:
    tags: docker
    stage: build
    script:
     - cd CI/scripts
     - make build
     - make add_libad9361
     - make gen_tlbx
     - cd ../..
     - mkdir mltbx
     - ls *.mltbx
     - cp *.mltbx mltbx/
    artifacts:
        paths:
            - hdl_wa_bsp/
            - mltbx/

# Future branches
build:master:
    tags: docker
    stage: build
    script:
     - cd CI/scripts
     - make build MLRELEASE=R2018b HDLBRANCH=master
     - cd ../..
    allow_failure: true
    artifacts:
        paths:
            - hdl_wa_bsp/

# Tests
test:2018_R1:
    tags: docker
    stage: test
    dependencies:
     - build:2018_R1
    script:
     - cd CI/scripts
#     - make test
     - make zip
    artifacts:
        paths:
            - zip/
        reports:
            junit: test/BSPTestResults.xml

test_installer:2018_R1_Installer:
    tags: docker
    stage: test_installer
    dependencies:
     - build:2018_R1
    script:
     - cp mltbx/* .
     - pwd
     - ls
     - ls *.mltbx
     - cd CI/scripts
     - make test_installer
    artifacts:
        paths:
            - mltbx/
            - zip/
        reports:
            junit: test/BSPTestResults.xml

test_hardware:Streaming_Hardware:
    tags:
     - docker
     - hardware
#    only:
#     - schedules
    stage: test_hardware
    dependencies:
     - build:2018_R1
    script:
     - cd CI/scripts
     - make test_streaming
    artifacts:
        paths:
            - logs/

# Deploy
deploy:
    tags: docker
    stage: deploy
    dependencies:
     - test:2018_R1
     - test_installer:2018_R1_Installer
    script:
     - echo "Complete"
    artifacts:
        paths:
            - mltbx/


